"""
Core utilities module for MetaTrader Python Framework.

This module provides various utility functions and decorators for common
operations including retry logic, validation, caching, and data manipulation.
"""

# Decorators
from .decorators import (
    async_retry,
    async_timeout,
    cache,
    deprecated,
    measure_time,
    property_cached,
    rate_limit,
    retry,
    singleton,
    thread_safe,
    timeout,
    validate_types,
)

# Validators
from .validators import (
    BaseValidator,
    ChoiceValidator,
    DateValidator,
    EmailValidator,
    LengthValidator,
    PathValidator,
    PriceValidator,
    RangeValidator,
    RegexValidator,
    TradingSymbolValidator,
    TypeValidator,
    UrlValidator,
    ValidationResult,
    VolumeValidator,
    create_validator_chain,
    validate_all,
)

# Helpers
from .helpers import (
    backup_file,
    calculate_file_hash,
    calculate_percentage,
    calculate_pip_value,
    calculate_string_hash,
    camel_to_snake,
    chunk_list,
    clamp,
    datetime_to_timestamp,
    directory_exists,
    ensure_directory,
    file_exists,
    flatten_list,
    format_bytes,
    format_datetime,
    format_price,
    generate_random_string,
    generate_uuid,
    get_env_var,
    get_file_modification_time,
    get_file_size,
    get_memory_usage,
    get_platform_info,
    get_python_version,
    group_by,
    is_number,
    json_serialize,
    load_json,
    load_pickle,
    normalize_symbol,
    parse_datetime,
    read_text_file,
    remove_duplicates,
    round_decimal,
    safe_divide,
    sanitize_filename,
    save_json,
    save_pickle,
    set_env_var,
    snake_to_camel,
    timestamp_to_datetime,
    truncate_string,
    utc_now,
    write_text_file,
)

__all__ = [
    # Decorators
    "retry",
    "async_retry",
    "timeout",
    "async_timeout",
    "cache",
    "rate_limit",
    "measure_time",
    "deprecated",
    "validate_types",
    "singleton",
    "thread_safe",
    "property_cached",
    # Validators
    "BaseValidator",
    "ValidationResult",
    "TypeValidator",
    "RangeValidator",
    "LengthValidator",
    "RegexValidator",
    "EmailValidator",
    "UrlValidator",
    "DateValidator",
    "ChoiceValidator",
    "PathValidator",
    "TradingSymbolValidator",
    "PriceValidator",
    "VolumeValidator",
    "validate_all",
    "create_validator_chain",
    # Helpers
    "utc_now",
    "timestamp_to_datetime",
    "datetime_to_timestamp",
    "format_datetime",
    "parse_datetime",
    "generate_random_string",
    "generate_uuid",
    "sanitize_filename",
    "truncate_string",
    "camel_to_snake",
    "snake_to_camel",
    "round_decimal",
    "calculate_percentage",
    "clamp",
    "is_number",
    "chunk_list",
    "flatten_list",
    "remove_duplicates",
    "group_by",
    "ensure_directory",
    "file_exists",
    "directory_exists",
    "get_file_size",
    "get_file_modification_time",
    "read_text_file",
    "write_text_file",
    "backup_file",
    "load_json",
    "save_json",
    "json_serialize",
    "save_pickle",
    "load_pickle",
    "calculate_file_hash",
    "calculate_string_hash",
    "get_python_version",
    "get_platform_info",
    "get_memory_usage",
    "format_bytes",
    "get_env_var",
    "set_env_var",
    "normalize_symbol",
    "calculate_pip_value",
    "format_price",
    "safe_divide",
]