indicators:
  rsi:
    period: 14
    enabled: true
  macd:
    fast_period: 12
    slow_period: 26
    signal_period: 9
    enabled: true
  bollinger_bands:
    period: 20
    deviation: 2.0
    enabled: true
  stochastic:
    k_period: 14
    d_period: 3
    slowing: 3
    enabled: false
