patterns:
  doji:
    enabled: true
    body_ratio_threshold: 0.1
  hammer:
    enabled: true
    body_ratio_threshold: 0.3
    shadow_ratio_threshold: 2.0
  shooting_star:
    enabled: true
    body_ratio_threshold: 0.3
    shadow_ratio_threshold: 2.0
  engulfing:
    enabled: true
    min_body_ratio: 0.5
