# Testing Environment Configuration
# MetaTrader Python Framework

environment: testing
debug: false

# Database settings for testing
database:
  url: "sqlite:///:memory:"  # In-memory database for tests
  echo: false

# Logging settings for testing
logging:
  level: WARNING
  file_path: "logs/test.log"
  format: simple

# MT5 settings for testing
mt5:
  enabled: false  # Disable MT5 connection in tests

# Trading settings for testing
trading:
  enabled: false  # Disable trading in tests

# API settings for testing
api:
  enabled: false  # Disable API in tests

# Notification settings for testing
notifications:
  enabled: false  # Disable notifications in tests

# GUI settings for testing
gui:
  enabled: false  # Disable GUI in tests

# Backup settings for testing
backup:
  enabled: false  # Disable backups in tests

# Performance settings for testing
performance:
  async_workers: 1
  thread_pool_size: 2

# Market data settings for testing
market_data:
  cache_enabled: false  # Disable caching in tests
  historical_data_days: 1  # Minimal data for tests